### ISSUE TITLE
\u0026 encoding in url strings

### ISSUE THREAD

**Issue by AshKash** [lauriro/json-lite#7]
Some JSON encoders encode strings. e.g. URLs with "&" are encoded:
"...device=iphone\u0026debug=1\u0026cache=true..."
This breaks json-lite as the links are no longer clickable nor copy-paste-browseable.

This is an awesome plugin and much faster than JSONView, please address the bug.

**Comment by lauriro** [comment]
Link href-s fixed in v0.20

**Comment by AshKash** [comment]
I edited Library/Caches/com.apple.Safari/Extensions/json-lite.safariextension/content.js locally and patched it but it still does not work.
Gist link for testing: https://gist.githubusercontent.com/AshKash/a7437a7a65c9a9adeaf74e2e6ed44942/raw/364e168ef9bd446aa834e13416c1a43f77df538b/test.json

**Comment by AshKash** [comment]
When can we update to 0.20 as the Safari web store still has 0.19.

I found that Safari downloads a clean copy of the extension into the cache directory every time it is started. So this might not be a bug in json-lite.

**Comment by lauriro** [comment]
You can install it manually while apple reviews it
https://www.litejs.com/pub/json-lite.safariextz

**Comment by AshKash** [comment]
Thanks! Clicking on these links work now. Minor nit is that they display as \u0026 instead of &.

**Comment by lauriro** [comment]
This is intentional, as a developer I want to see exact response from backend.
Copying link address should give a working link.

**Comment by linkfei** [comment]
<img width="551" alt="1" src="https://user-images.githubusercontent.com/12987627/36980561-9fe7c538-20c5-11e8-8c0e-12dfaaec106f.png">
This problem still exists, can not correctly display Chinese.

**Comment by lauriro** [comment]
The fix was for clickable url links, displaying has not been changed.

As a developer I want to see exact response from backend, so I could fix unnecessary escapes.
JSON does not require to escape unicode. In my view your JSON is broken.

You can select escaped text decode it with `right click` -> `JSON Lite` -> `Decode` -> `Unicode`
(If i remember correctly and context menu works is Safari).

In newer version there is an option `Auto-unescape strings` but I have no idea when Safari version can be updated, I have no access to osx. You can try a newer version with Firefox/Chrome/Opera.

**Comment by linkfei** [comment]
<img width="295" alt="1" src="https://user-images.githubusercontent.com/12987627/37069963-93ccf684-21f0-11e8-86d6-050d59f899df.png">

No **JSON Lite** option found 😰
